name: Android APK

on:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: ✅ Vérification des dépendances
        run: |
          for cmd in gradle; do
            if ! command -v $cmd &> /dev/null; then
              echo "❌ gradle manquant"
              exit 1
            fi
            echo "✅ gradle trouvé"
          done

      - name: Construire l'APK
        run: |
          cd platform/android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: TestApp-debug.apk
          path: platform/android/app/build/outputs/apk/debug/app-debug.apk
