name: Build for iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.6.3

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ninja
          pip3 install aqtinstall

      - name: Install Qt for iOS
        run: |
          python3 -m aqt install-qt mac desktop ${{ env.QT_VERSION }} ios --outputdir $HOME/Qt

      - name: Configure CMake
        run: |
          cmake -S . -B build/ios \
            -DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
            -DCMAKE_PREFIX_PATH=$HOME/Qt/${{ env.QT_VERSION }}/ios \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -G Ninja

      - name: Build
        run: cmake --build build/ios
