name: Build multiplateforme

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Compilation sur ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    timeout-minutes: 25

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installer les dépendances Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-xkb-dev

      - name: Vérification des dépendances (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Vérification des outils requis..."
          for cmd in cmake ninja ctest; do
            if ! command -v $cmd &> /dev/null; then
              echo "❌ $cmd est manquant"
              exit 1
            fi
            echo "✅ $cmd trouvé"
          done

      - name: Vérification des dépendances (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $tools = @("cmake", "ninja", "ctest")
          foreach ($cmd in $tools) {
            if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
              Write-Host "❌ $cmd est manquant"
              exit 1
            } else {
              Write-Host "✅ $cmd trouvé"
            }
          }

      - name: Installer Qt via install-qt-action (Linux/macOS)
        if: runner.os != 'Windows'
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3

      - name: Configurer le projet
        shell: bash
        run: |
          case "${{ runner.os }}" in
            Linux)   QT_PATH="$HOME/Qt/6.8.3/gcc_64" ;;
            macOS)   QT_PATH="$HOME/Qt/6.8.3/clang_64" ;;
            Windows) QT_PATH="$HOME/Qt/6.8.3/msvc2019_64" ;;
            *)       echo "Unsupported OS"; exit 1 ;;
          esac
          echo "Using Qt path: $QT_PATH"
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$QT_PATH"

      - name: Compiler le projet
        run: cmake --build build --parallel

      - name: Exécuter les tests
        run: ctest --test-dir build --output-on-failure --parallel $(nproc || 2)
