name: Build WebAssembly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QT_VERSION: 6.6.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          pip install aqtinstall

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: Install Qt for WebAssembly
        run: |
          python3 -m aqt install-qt linux desktop $QT_VERSION wasm_32 --outputdir $HOME/Qt

      - name: Configure CMake
        run: |
          source emsdk/emsdk_env.sh
          cmake -S . -B build \
            -DCMAKE_TOOLCHAIN_FILE=cmake/wasm.toolchain.cmake \
            -DCMAKE_PREFIX_PATH=$HOME/Qt/$QT_VERSION/wasm_32 \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build
