name: Build Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          pip install aqtinstall

      - name: Install Qt for Android
        run: |
          python3 -m aqt install-qt linux android 6.6.3 android_armv7 --outputdir $HOME/Qt

      - name: Configure CMake
        run: |
          cmake --preset=android

      - name: Build project
        run: |
          cmake --build build/android
