name: Build for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.6.3

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ninja
          pip3 install aqtinstall

      - name: Install Qt
        run: |
          python3 -m aqt install-qt mac desktop ${{ env.QT_VERSION }} clang_64 --outputdir $HOME/Qt

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_PREFIX_PATH=$HOME/Qt/${{ env.QT_VERSION }}/clang_64 \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -G Ninja

      - name: Build
        run: cmake --build build
