name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ninja
          pip3 install aqtinstall

      - name: Install Qt for iOS
        run: |
          python3 -m aqt install-qt mac desktop 6.6.3 ios --outputdir $HOME/Qt

      - name: Configure CMake
        run: |
          cmake --preset=ios

      - name: Build project
        run: |
          cmake --build build/ios
