name: Build for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  QT_VERSION: 6.6.3
  ANDROID_ABI: armeabi-v7a
  ANDROID_PLATFORM: android-21

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          pip install aqtinstall

      - name: Install Qt for Android
        run: |
          python3 -m aqt install-qt linux android ${{ env.QT_VERSION }} ${{ env.ANDROID_ABI }} --outputdir $HOME/Qt

      - name: Configure CMake
        run: |
          cmake -S . -B build/android \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ env.ANDROID_ABI }} \
            -DANDROID_PLATFORM=${{ env.ANDROID_PLATFORM }} \
            -DCMAKE_PREFIX_PATH=$HOME/Qt/${{ env.QT_VERSION }}/${{ env.ANDROID_ABI }} \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -G Ninja

      - name: Build
        run: cmake --build build/android
