name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Installer Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3

      - name: Configurer le projet avec CMake
        run: |
          QT_PATH="$HOME/Qt/6.8.3/gcc_64"
          echo "Using Qt path: $QT_PATH"
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_PREFIX_PATH="$QT_PATH"

      - name: Compiler le projet
        run: cmake --build build

      - name: Exécuter les tests
        run: |
          cd build
          ctest --output-on-failure
