name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
      - name: Installer les dépendances
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Compiler l'application
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          cmake --build build
      - name: Exécuter les tests
        run: |
          cd build
          ctest
