name: Clang Format Check & Auto Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'  # chaque lundi à 3h du matin

permissions:
  contents: write  

jobs:
  clang-format:
    name: Clang Format & Auto Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run clang-format-lint-action
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          extensions: 'cpp,h'
          clangFormatVersion: 14
          inplace: true  
          style: file     

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Prepare push authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m " Apply automatic clang-format"
          git push origin HEAD:main
