name: Clang-Tidy Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang-tidy:
    name: Run clang-tidy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cmake ninja-build

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3

      - name: Configure CMake
        run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: |
          cp build/compile_commands.json .
          clang-tidy src/*.cpp -- -I./src -std=c++20

      - name: Cleanup
        run: rm -f compile_commands.json
