name: Clang-Tidy Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build
          pip install aqtinstall

      - name: Install Qt
        run: |
          python3 -m aqt install-qt linux desktop 6.6.3 gcc_64 --outputdir $HOME/Qt

      - name: Configure CMake
        run: cmake -S . -B build \
                 -DCMAKE_PREFIX_PATH=$HOME/Qt/6.6.3/gcc_64 \
                 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run Clang-Tidy
        run: clang-tidy -p build $(find . -name '*.cpp')
