name: Clang Format PR Auto Fix

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  auto-format:
    name: Clang Format on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          extensions: 'cpp,h'
          clangFormatVersion: 14
          inplace: true
          style: file

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate for push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit and push format changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "🔧 Apply clang-format"
          git push origin HEAD:${{ github.head_ref }}
