name: Clang Format Daily

on:
  push:
    branches:
      - main # or your default branch
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Necessary to get all history for diffing

    - name: Set up ClangFormat
      uses: DoozyX/clang-format-lint-action@v0.17
      with:
        clangFormatVersion: '14' # or your desired version. Ensure it matches your .clang-format
        #checkName: 'ClangFormat'
        style: file # Uses .clang-format file in the repo root.
        files: '*.cpp *.h' # Files to check.
        inplace: 'true'
        # If you want to commit changes directly to the branch, use the following:
        # commit: true
        # commitMessage: 'Apply clang-format'
        # If you want to create a pull request with the changes, use the following:
        # pullRequest: true
        # pullRequestTitle: 'Apply clang-format'
        # pullRequestBranch: 'clang-format-patch' # Name of branch to create for the PR

    - name: Check for changes
      id: check-changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "::set-output name=has_changes::true"
        else
          echo "::set-output name=has_changes::false"
        fi

    - name: Commit changes (If needed)
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Apply clang-format"
        git push origin HEAD:${{ github.ref_name }}
