name: Clang-Tidy Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  QT_VERSION: 6.8.3

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build
          pip install aqtinstall

      - name: Install Qt with required modules from mirror
        run: |
          python3 -m aqt install-qt linux desktop ${{ env.QT_VERSION }} --outputdir $HOME/Qt --modules qtbase qtdeclarative qtshadertools qtquick3d qt5compat --base https://mirrors.dotsrc.org/qtproject/

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_PREFIX_PATH=$HOME/Qt/${{ env.QT_VERSION }}/gcc_64 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run Clang-Tidy
        run: |
          clang-tidy -p build $(find . -name '*.cpp')
