name: Clang-Tidy

on:
  pull_request:
    branches: [ main ]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'

      - name: Configure for tidy
        run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Run clang-tidy
        run: clang-tidy -p build $(find src tests -name '*.cpp')
