name: Clazy Qt Analyzer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clazy-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build clazy
          pip install aqtinstall

      - name: Install Qt
        run: |
          python3 -m aqt install-qt linux desktop 6.6.3 --outputdir $HOME/Qt \
            --modules qtbase qtdeclarative qtshadertools qtquick3d qt5compat

      - name: Configure project with Clazy
        run: cmake -B build -DCMAKE_CXX_COMPILER=clazy \
                   -DCMAKE_PREFIX_PATH=$HOME/Qt/6.6.3/gcc_64

      - name: Build project
        run: cmake --build build
