name: Clazy Qt Analyzer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clazy-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build qtbase5-dev qtdeclarative5-dev clazy

      - name: Configure project with Clazy
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=clazy -DCMAKE_BUILD_TYPE=Debug

      - name: Build project
        run: |
          cmake --build build
