name: Packaging (CPack)

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'

      - name: Configure with CPack
        run: |
          QT_PATH="$HOME/Qt/6.8.3/gcc_64"
          echo "Using Qt path: $QT_PATH"
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$QT_PATH" -DCPACK_GENERATOR=DEB
          cmake --build build
          cmake --build build --target package

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: TestApp-deb
          path: build/*.deb
