name: CppCheck Analysis

on:
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --std=c++20 --inline-suppr --force \
            src/ tests/ qml/ \
            2> cppcheck-report.txt || true
          head cppcheck-report.txt
