name: Cppcheck Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cppcheck:
    name: Run cppcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run cppcheck on src and tests
        run: |
          cppcheck --enable=all --inconclusive --std=c++20 \
                   --language=c++ \
                   --inline-suppr \
                   --suppress=missingIncludeSystem \
                   --force \
                   --quiet \
                   src/ tests/ qml/
