name: Build Linux DEB Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installer dépendances
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3

      - name: Compiler l'application
        run: |
          QT_PATH="$HOME/Qt/6.8.3/gcc_64"
          echo "Using Qt path: $QT_PATH"
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$QT_PATH"
          cmake --build build

      - name: Préparer la structure du paquet
        run: |
          mkdir -p installer/linux/usr/local/bin
          mkdir -p installer/linux/usr/share/applications
          mkdir -p installer/linux/usr/share/icons/hicolor/64x64/apps
          cp build/TestApp installer/linux/usr/local/bin/
          cp installer/linux/testapp.desktop installer/linux/usr/share/applications/
          cp installer/linux/testapp.png installer/linux/usr/share/icons/hicolor/64x64/apps/testapp.png

      - name: Construire le .deb
        run: dpkg-deb --build installer/linux testapp_1.0.0_amd64.deb

      - name: Upload de l’installateur
        uses: actions/upload-artifact@v4
        with:
          name: testapp-debian-installer
          path: testapp_1.0.0_amd64.deb
