name: Build macOS DMG Installer

on:
  push:
    branches: [main]

jobs:
  build-dmg:
    runs-on: macos-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: ✅ Vérification des dépendances
        run: |
          for cmd in cmake hdiutil; do
            if ! command -v $cmd &> /dev/null; then
              echo "❌ $cmd est manquant"
              exit 1
            fi
            echo "✅ $cmd trouvé"
          done

      - name: Compiler l’application
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Créer .dmg
        run: |
          cd installer/macos
          chmod +x create-dmg.sh
          ./create-dmg.sh
