name: Build macOS DMG Installer

on:
  push:
    branches: [main]

jobs:
  build-dmg:
    runs-on: macos-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: Installer Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3

      - name: Compiler l’application
        run: |
          QT_PATH="$HOME/Qt/6.8.3/clang_64"
          echo "Using Qt path: $QT_PATH"
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$QT_PATH"
          cmake --build build --config Release

      - name: Créer .dmg
        run: |
          cd installer/macos
          chmod +x create-dmg.sh
          ./create-dmg.sh
