name: QDoc Documentation

on:
  push:
    branches: [ main ]

jobs:
  qdoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'

      - name: Build QDoc
        run: |
          QT_PATH="$HOME/Qt/6.8.3/gcc_64"
          echo "Using Qt path: $QT_PATH"
          mkdir -p build-doc
          cd build-doc
          qdoc ../docs/testapp.qdocconf

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v1
        with:
          path: build-doc/html
