name: Génération Documentation QDoc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  qdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installer Python et QDoc
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install --upgrade qdoc-plugin

      - name: Générer la doc QDoc
        run: |
          mkdir -p docs_output
          qdoc \
            -project CMakeLists.txt \
            -output docs_output

      - name: Publier sur GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs_output

      - name: Publier artefacts
        uses: actions/upload-artifact@v4
        with:
          name: qdoc-output
          path: docs_output
