name: 📦 Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du dépôt
        uses: actions/checkout@v4

      - name: ✅ Vérification des dépendances
        run: |
          for cmd in cmake ninja zip; do
            if ! command -v $cmd &> /dev/null; then
              echo "❌ $cmd est manquant"
              exit 1
            fi
            echo "✅ $cmd trouvé"
          done

      - name: Extraire version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Compiler le projet
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Créer la release
        uses: softprops/action-gh-release@v1
        with:
          name: "Version ${{ env.VERSION }}"
          tag_name: "${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ajouter les artefacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.msi
            *.dmg
            platform/android/app/build/outputs/apk/debug/app-debug.apk
            web-dist/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
