name: Create Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'

      - name: Configure & Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Package
        run: cpack --config build/CPackConfig.cmake

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.zip
