name: Publish GitHub Release with Artifacts

on:
  push:
    tags:
      - 'v*.*.*'  # Déclenchement uniquement sur un tag de version

permissions:
  contents: write

env:
  QT_VERSION: 6.8.3
  BUILD_TYPE: Release

jobs:
  build:
    name: Build and package
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}

      - name: Install packaging tools (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev rpm

      - name: Configure project
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build application
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Generate packages
        run: cmake --build build --target package

      - name: Upload artifacts for release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.zip
            build/*.msi
            build/*.dmg
            build/*.deb
            build/*.rpm
            build/*.tar.gz
            build/*.apk
            build-wasm/*.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
