name: Tests unitaires Qt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'

      - name: Configure project
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build tests
        run: cmake --build build --target CppTest QtTests QmlTests

      - name: Run C++ tests
        run: ./build/tests/cpp-tests/CppTest

      - name: Run Qt tests
        run: ./build/tests/qt-tests/QtTests

      - name: Run QML tests
        run: ./build/tests/qml-tests/QmlTests
