name: C++ Test Coverage (LLVM)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  QT_VERSION: 6.8.3

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installer Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}

      - name: Définir QT_PATH
        run: echo "QT_PATH=$HOME/Qt/${{ env.QT_VERSION }}/gcc_64" >> $GITHUB_ENV

      - name: Installer dépendances
        run: sudo apt-get update && sudo apt-get install -y clang llvm lcov ninja-build

      - name: Configurer CMake pour couverture
        run: cmake -B build-coverage \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_CXX_FLAGS="--coverage -fprofile-instr-generate -fcoverage-mapping" \
          -DCMAKE_EXE_LINKER_FLAGS="--coverage -fprofile-instr-generate -fcoverage-mapping" \
          -DCMAKE_PREFIX_PATH="$QT_PATH"

      - name: Compiler
        run: cmake --build build-coverage

      - name: Exécuter tests & générer profil
        run: |
          cd build-coverage/tests/cpp-tests
          LLVM_PROFILE_FILE="CppTest.profraw" ./CppTest
          llvm-profdata merge -output=CppTest.profdata CppTest.profraw

      - name: Exporter couverture
        run: |
          cd build-coverage/tests/cpp-tests
          llvm-cov export ./CppTest -instr-profile=CppTest.profdata -format=lcov > coverage.info

      - name: Publier rapport de couverture
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build-coverage/tests/cpp-tests/coverage.info
