name: C++ Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug
  QT_VERSION: 6.8.3

jobs:
  coverage:
    name: Coverage (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang gcovr lcov ninja-build
          pip install aqtinstall

      - name: Install Qt with required modules
        run: |
          python3 -m aqt install-qt linux desktop ${{ env.QT_VERSION }} --outputdir $HOME/Qt --modules qtbase qtdeclarative qtshadertools qtquick3d qt5compat

      - name: Configure CMake with coverage flags
        run: |
          cmake -B build -DCMAKE_PREFIX_PATH=$HOME/Qt/${{ env.QT_VERSION }}/gcc_64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="--coverage -fprofile-instr-generate -fcoverage-mapping" -DCMAKE_EXE_LINKER_FLAGS="--coverage -fprofile-instr-generate -fcoverage-mapping"

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
          cd ..

      - name: Generate coverage report with gcovr
        run: |
          gcovr --root . --filter src/
::contentReference[oaicite:12]{index=12}
 
