name: Qt Translations

on:
  push:
    paths:
      - '**/*.ts'
      - '**/*.qml'
      - '**/*.cpp'
      - '**/*.h'

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'

      - name: Update .ts files
        run: |
          lupdate src/ qml/ -ts translations/fr.ts

      - name: Compile .ts files
        run: |
          lrelease translations/fr.ts -qm translations/fr.qm
