name: Qt Translations

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  translations:
    name: Generate Qt Translation Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt tools
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3

      - name: Create translations folder if missing
        run: mkdir -p translations

      - name: Extract translatable strings (.ts)
        run: |
          lupdate src/ qml/ -ts translations/app_fr.ts

      - name: Compile translations (.qm)
        run: |
          lrelease translations/app_fr.ts
