name: Build WebAssembly (WASM)

on:
  push:
    branches: [main]

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: ✅ Vérification des dépendances
        run: |
          for cmd in emcmake emcc cmake; do
            if ! command -v $cmd &> /dev/null; then
              echo "❌ $cmd est manquant"
              exit 1
            fi
            echo "✅ $cmd trouvé"
          done

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.27

      - name: Compiler Web
        run: |
          emcmake cmake -S platform/web -B build-web
          cmake --build build-web
