name: Build Windows Installer

on:
  push:
    branches: [main]

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Vérifier les dépendances
        run: |
          if (!(Get-Command cmake -ErrorAction SilentlyContinue)) {
            Write-Error "❌ cmake non trouvé"; exit 1
          }
          if (!(Get-Command candle -ErrorAction SilentlyContinue)) {
            Write-Error "❌ WiX (candle.exe) non trouvé"; exit 1
          }
          if (!(Get-Command light -ErrorAction SilentlyContinue)) {
            Write-Error "❌ WiX (light.exe) non trouvé"; exit 1
          }
          Write-Output "✅ Toutes les dépendances trouvées"

      - name: Installer Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3

      - name: Compilation + MSI
        run: |
          $QT_PATH = "${env:USERPROFILE}\Qt\6.8.3\msvc2019_64"
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$QT_PATH"
          cmake --build build
          cd installer/windows
          ./build-msi.bat
