name: Build Windows Installer

on:
  push:
    branches: [main]

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: ✅ Vérification des dépendances
        run: |
          if (!(Get-Command cmake -ErrorAction SilentlyContinue)) {
            Write-Error "❌ cmake non trouvé"; exit 1
          }
          if (!(Get-Command candle -ErrorAction SilentlyContinue)) {
            Write-Error "❌ WiX (candle.exe) non trouvé"; exit 1
          }
          if (!(Get-Command light -ErrorAction SilentlyContinue)) {
            Write-Error "❌ WiX (light.exe) non trouvé"; exit 1
          }
          Write-Output "✅ Toutes les dépendances trouvées"

      - name: Compilation + MSI
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cd installer/windows
          ./build-msi.bat
