name: Build Windows Installer

on:
  push:
    branches: [main]

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer WiX Toolset
        run: choco install wix -y

      - name: Compiler l'application
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Créer le fichier .msi
        run: |
          candle installer/windows/installer.wxs
          light installer.wixobj -o TestAppInstaller.msi

      - name: Upload du fichier MSI
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: TestAppInstaller.msi
